package com.demo;

// Generated Jun 20, 2017 12:15:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private String name;
	private String city;
	private float marks;

	public Student() {
	}

	public Student(String name, String city, float marks) {
		this.name = name;
		this.city = city;
		this.marks = marks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public float getMarks() {
		return this.marks;
	}

	public void setMarks(float marks) {
		this.marks = marks;
	}

}
