package com.hib.demo;

// Generated Jun 5, 2017 3:15:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private EmpId id;

	public Emp() {
	}

	public Emp(EmpId id) {
		this.id = id;
	}

	public EmpId getId() {
		return this.id;
	}

	public void setId(EmpId id) {
		this.id = id;
	}

}
