package com.hib.demo;

// Generated Jun 6, 2017 4:20:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * Emp generated by hbm2java
 */
public class Emp implements java.io.Serializable {

	private Integer id;
	private String name;
	private String addr;

	public Emp() {
	}

	public Emp(String name, String addr) {
		this.name = name;
		this.addr = addr;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

}
