package com.demo;

// Generated Jun 18, 2017 1:02:32 AM by Hibernate Tools 3.4.0.CR1

/**
 * EmpTbl generated by hbm2java
 */
public class EmpTbl implements java.io.Serializable {

	private Integer id;
	private String address;
	private String email;
	private String name;
	private String telephone;

	public EmpTbl() {
	}

	public EmpTbl(String address, String email, String name, String telephone) {
		this.address = address;
		this.email = email;
		this.name = name;
		this.telephone = telephone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
