package com.demo;

import javax.persistence.NamedNativeQuery;
import javax.persistence.NamedQuery;

// Generated Jun 19, 2017 5:11:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */

@NamedQuery(name="Student.byId", query="from Student where id = ?")
@NamedNativeQuery(name="Student.byName", query="select * from Student where name = ?", resultClass=Student.class)
public class Student implements java.io.Serializable {

	private Integer id;
	private String name;
	private String city;

	public Student() {
	}

	public Student(String name, String city) {
		this.name = name;
		this.city = city;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
