package com.hib.demo;

// Generated Jun 5, 2017 10:00:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Hydra generated by hbm2java
 */
public class Hydra implements java.io.Serializable {

	private Integer id;
	private String name;
	private String city;

	public Hydra() {
	}

	public Hydra(String name, String city) {
		this.name = name;
		this.city = city;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
